In [1]:
import numpy as np
##1.  Create array of shape (10,10) with random uint value.
a1 = np.random.randint( 0 , 256 ,( 10 , 10 ), dtype='uint8' )

##2.  Print its shape size and propeties
print("shape = ", a1.shape)
print("size = ", a1.size)
print("dimension = ", a1.ndim)

shape =  (10, 10)
size =  100
dimension =  2


In [13]:
## 3. 
print(a1[2])
arr_third_row_to_last = arr3_last = a1[3:]
sum_third_row_to_last = np.sum(arr_third_row_to_last, axis = 1)

print("Sum of each row from third row to the last row ",sum_third_row_to_last)
print("Sum of all row from third to last row : ",np.sum(arr_third_row_to_last))

[ 80  73 154   5 166 110  21  61  80  42]
Sum of each row from third row to the last row  [ 995 1117 1307 1182 1092 1169 1425]
Sum of all row from third to last row :  8287


In [4]:
##4. Average of the columns
print(a1)

## average of each column
total_column = (a1.sum(axis=0))# aum the value along each rows, giving the total value for each column
print(total_column)

total_len = len(a1)
print(total_len)

## average of all column
average= (np.sum(total_column)/total_len)
print(average) 

[[244 204  15 155 131 165  43  50  34 201]
 [112 250 215 138 177 212 156 225 203 231]
 [ 80  73 154   5 166 110  21  61  80  42]
 [ 20 205 196  47  43  37   4 136 103 204]
 [ 21  81 147  94 175  59 208  69 255   8]
 [177  96 228 246   9   4 180 168 116  83]
 [121 135 205  22 126 107 117 150  69 130]
 [212  90  49  81  71  77 236 238  10  28]
 [242 143   1 140  17  16 149 123 181 157]
 [ 93 203 134 174 123 225 137  33 151 152]]
[1322 1480 1344 1102 1038 1012 1251 1253 1202 1236]
10
1224.0
