In [25]:
import numpy as np
np.random.seed(2)

a = np.random.randint(0,256,(6,6))
print(a)

a_inv = np.copy(a)
a_inv = np.linalg.inv(a)
print(a_inv)

aa = np.dot(a,a_inv)

np.allclose(np.dot(a, a_inv), np.eye(6))





[[168  15 237  72  22  43]
 [210  75 104   7 162 177]
 [ 95  75 213  47  63  31]
 [218 148 124 116  37 167]
 [195 102   4 170 107  51]
 [103  38 234  33  58 124]]
[[ 7.95123333e-03  4.19991509e-03 -9.34339134e-04  1.96100012e-03
  -2.66691178e-03 -1.00628872e-02]
 [-5.49186329e-03  7.55932378e-06  1.09626666e-02  5.97698097e-03
  -3.32182147e-03 -7.53043121e-03]
 [ 6.14287358e-04 -1.17379557e-03  2.62325818e-03 -8.01201875e-04
  -8.22068385e-04  2.22381174e-03]
 [-2.14088679e-03 -6.23835322e-03 -5.13050077e-03 -2.19696163e-03
   7.89804016e-03  1.06401994e-02]
 [-4.18255457e-03  2.71646076e-03  2.88993486e-03 -6.56440328e-03
   4.60254549e-03  3.79817613e-03]
 [-3.55477452e-03 -8.86285593e-04 -7.52013315e-03  1.70651672e-03
   5.29856190e-04  9.92613729e-03]]


True