##Numpy

numpy means numeric in python.
It is used to handle matrix and array operation involving numbers.
Its similar to list but more advanced and only used for numerical operations.

Installation of numpy, scipy and pandas

In [4]:
!pip install numpy

In [31]:
def array_propeties(a):
    print("array = \n", a)
    print("dimension = ", a.ndim)
    print("shape = ",a.shape)
    print("data type =",a.dtype)
    print("size = ", a.size)
    print()

In [10]:
# import a package an give it an alias as np
# doing this we can type np when using the packages functionns
import numpy as np

# Creating a rowsxcolumn numpy array
a = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(a)
# number of dimension
print(a.ndim)
# shape of array ie 3x3
print(a.shape)
# number of elements
print(a.size)
print(type(a))
# creating a 3x3 python list
alist = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
print(alist
)
print(type(alist))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [17]:
import numpy as np

## converting python list to numpy array
blist = [1,2,3,4]
print(blist)
b = np.array(blist)
print(b)
print("array = \n", b)
print("dimension = ", b.ndim)
print("shape = ",b.shape)
print("data type =",b.dtype)
print("size = ", b.size)
print()

# if list contain string everything is converted to a datatype that is a union of value since we mix different datatype
clist = [1, "ali", 2, "python"]
c = np.array(clist)
print("array = \n", c)
print("dimension = ", c.ndim)
print("shape = ",c.shape)
# 
print("data type =",c.dtype)
print("size = ", c.size)
print()


[1, 2, 3, 4]
[1 2 3 4]
array = 
 [1 2 3 4]
dimension =  1
shape =  (4,)
data type = int32
size =  4

array = 
 ['1' 'ali' '2' 'python']
dimension =  1
shape =  (4,)
data type = <U11
size =  4



In [15]:
import numpy as np

# python list can only get length of the leading dimension
alist = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ] 
print(alist)
print(len(alist))

a = np.array(alist)
print("array = \n", a)
print("dimension = ", a.ndim)
print("shape = ",a.shape)
print("data type =",a.dtype)
print("size = ", a.size)
print()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3
array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9



In [34]:
## creating np array of different shapes
# one by 3
import numpy as np
onebythree = np.array([[11,12,13]])

array_propeties(onebythree)

fourbyone = np.array([[21],[22],[23],[24]])
array_propeties(fourbyone)


array = 
 [[11 12 13]]
dimension =  2
shape =  (1, 3)
data type = int32
size =  3

array = 
 [[21]
 [22]
 [23]
 [24]]
dimension =  2
shape =  (4, 1)
data type = int32
size =  4



In [38]:
## Specifying datatype 

## initialize elements as float
a= np.array(
    [
        [11,12,13]
    ], dtype='float'
)

array_propeties(a)

## initialize elements as float32
a= np.array(
    [
        [11,12,13]
    ], dtype='float32'
)

array_propeties(a)

## initialize elements as int64
a= np.array(
    [
        [11,12,13]
    ], dtype='int64'
)

array_propeties(a)


## if no type are specified it will get the biggest datatype of elements
a= np.array(
    [   #in this case is a float32 or float64 depending on your os
        [11.,12,13]
    ]
)

array_propeties(a)


array = 
 [[11. 12. 13.]]
dimension =  2
shape =  (1, 3)
data type = float64
size =  3

array = 
 [[11. 12. 13.]]
dimension =  2
shape =  (1, 3)
data type = float32
size =  3

array = 
 [[11 12 13]]
dimension =  2
shape =  (1, 3)
data type = int64
size =  3

array = 
 [[11. 12. 13.]]
dimension =  2
shape =  (1, 3)
data type = float64
size =  3



In [40]:
a = np.array([
    [21],
    [22],
    [31],
    [0]
], dtype='float32')

array_propeties(a)

array = 
 [[21.]
 [22.]
 [31.]
 [ 0.]]
dimension =  2
shape =  (4, 1)
data type = float32
size =  4



In [41]:
## unsigned integer in 8 bits, uint8 datatype
# Min value is 0 and max value is 255 because 8 bit can only hold max 11111111 in 8 bit which is 255.


a = np.array([
    [21],
    [22],
    [31],
    [0]
], dtype='uint8')

array_propeties(a)

# int8 is a signed 8 bit
# min value is -128
# max is 127

array = 
 [[21]
 [22]
 [31]
 [ 0]]
dimension =  2
shape =  (4, 1)
data type = uint8
size =  4



In [47]:
## np.arange is similar to range()
import numpy as np

# seq_a = array of 1 to 10-1
seq_a = np.arange(1,10)
array_propeties(seq_a)

# like range(star,stop,step) np.arange(start,stop,step)
seq_a = np.arange(1,10,2)
array_propeties(seq_a)

array = 
 [1 2 3 4 5 6 7 8 9]
dimension =  1
shape =  (9,)
data type = int32
size =  9

array = 
 [1 3 5 7 9]
dimension =  1
shape =  (5,)
data type = int32
size =  5



In [52]:
a10 = np.arange(10)
print(a10)
for n in range(10):
    print(n,end=' | ')


for n in a10:
    print(n,end=' | ')

[0 1 2 3 4 5 6 7 8 9]
0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 

In [ ]:
start =1 
stop = 10+1
step =2
ar10b = np.arange(start,stop,step)

for n in ar10b:
    print(n,end='|')