##Numpy

numpy means numeric in python.
It is used to handle matrix and array operation involving numbers.
Its similar to list but more advanced and only used for numerical operations.

Installation of numpy, scipy and pandas

In [4]:
!pip install numpy

In [31]:
def array_propeties(a):
    print("array = \n", a)
    print("dimension = ", a.ndim)
    print("shape = ",a.shape)
    print("data type =",a.dtype)
    print("size = ", a.size)
    print()

In [10]:
# import a package an give it an alias as np
# doing this we can type np when using the packages functionns
import numpy as np

# Creating a rowsxcolumn numpy array
a = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(a)
# number of dimension
print(a.ndim)
# shape of array ie 3x3
print(a.shape)
# number of elements
print(a.size)
print(type(a))
# creating a 3x3 python list
alist = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
print(alist
)
print(type(alist))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [17]:
import numpy as np

## converting python list to numpy array
blist = [1,2,3,4]
print(blist)
b = np.array(blist)
print(b)
print("array = \n", b)
print("dimension = ", b.ndim)
print("shape = ",b.shape)
print("data type =",b.dtype)
print("size = ", b.size)
print()

# if list contain string everything is converted to a datatype that is a union of value since we mix different datatype
clist = [1, "ali", 2, "python"]
c = np.array(clist)
print("array = \n", c)
print("dimension = ", c.ndim)
print("shape = ",c.shape)
# 
print("data type =",c.dtype)
print("size = ", c.size)
print()


[1, 2, 3, 4]
[1 2 3 4]
array = 
 [1 2 3 4]
dimension =  1
shape =  (4,)
data type = int32
size =  4

array = 
 ['1' 'ali' '2' 'python']
dimension =  1
shape =  (4,)
data type = <U11
size =  4



In [15]:
import numpy as np

# python list can only get length of the leading dimension
alist = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ] 
print(alist)
print(len(alist))

a = np.array(alist)
print("array = \n", a)
print("dimension = ", a.ndim)
print("shape = ",a.shape)
print("data type =",a.dtype)
print("size = ", a.size)
print()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3
array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9



In [34]:
import numpy as np
onebythree = np.array([[11,12,13]])

array_propeties(onebythree)

fourbyone = np.array([[21],[22],[23],[24]])
array_propeties(fourbyone)


array = 
 [[11 12 13]]
dimension =  2
shape =  (1, 3)
data type = int32
size =  3

array = 
 [[21]
 [22]
 [23]
 [24]]
dimension =  2
shape =  (4, 1)
data type = int32
size =  4

