##Numpy

numpy means numeric in python.
It is used to handle matrix and array operation involving numbers.
Its similar to list but more advanced and only used for numerical operations.

Installation of numpy, scipy and pandas

In [4]:
!pip install numpy

In [8]:
def array_propeties(a):
    print("array = \n", a)
    print("dimension = ", a.ndim)
    print("shape = ",a.shape)
    print("data type =",a.dtype)
    print("size = ", a.size)
    print()

In [10]:
# import a package an give it an alias as np
# doing this we can type np when using the packages functionns
import numpy as np

# Creating a rowsxcolumn numpy array
a = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(a)
# number of dimension
print(a.ndim)
# shape of array ie 3x3
print(a.shape)
# number of elements
print(a.size)
print(type(a))
# creating a 3x3 python list
alist = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
print(alist
)
print(type(alist))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [17]:
import numpy as np

## converting python list to numpy array
blist = [1,2,3,4]
print(blist)
b = np.array(blist)
print(b)
print("array = \n", b)
print("dimension = ", b.ndim)
print("shape = ",b.shape)
print("data type =",b.dtype)
print("size = ", b.size)
print()

# if list contain string everything is converted to a datatype that is a union of value since we mix different datatype
clist = [1, "ali", 2, "python"]
c = np.array(clist)
print("array = \n", c)
print("dimension = ", c.ndim)
print("shape = ",c.shape)
# 
print("data type =",c.dtype)
print("size = ", c.size)
print()


[1, 2, 3, 4]
[1 2 3 4]
array = 
 [1 2 3 4]
dimension =  1
shape =  (4,)
data type = int32
size =  4

array = 
 ['1' 'ali' '2' 'python']
dimension =  1
shape =  (4,)
data type = <U11
size =  4



In [15]:
import numpy as np

# python list can only get length of the leading dimension
alist = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ] 
print(alist)
print(len(alist))

a = np.array(alist)
print("array = \n", a)
print("dimension = ", a.ndim)
print("shape = ",a.shape)
print("data type =",a.dtype)
print("size = ", a.size)
print()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3
array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9



In [34]:
## creating np array of different shapes
# one by 3
import numpy as np
onebythree = np.array([[11,12,13]])

array_propeties(onebythree)

fourbyone = np.array([[21],[22],[23],[24]])
array_propeties(fourbyone)


array = 
 [[11 12 13]]
dimension =  2
shape =  (1, 3)
data type = int32
size =  3

array = 
 [[21]
 [22]
 [23]
 [24]]
dimension =  2
shape =  (4, 1)
data type = int32
size =  4



In [38]:
## Specifying datatype 

## initialize elements as float
a= np.array(
    [
        [11,12,13]
    ], dtype='float'
)

array_propeties(a)

## initialize elements as float32
a= np.array(
    [
        [11,12,13]
    ], dtype='float32'
)

array_propeties(a)

## initialize elements as int64
a= np.array(
    [
        [11,12,13]
    ], dtype='int64'
)

array_propeties(a)


## if no type are specified it will get the biggest datatype of elements
a= np.array(
    [   #in this case is a float32 or float64 depending on your os
        [11.,12,13]
    ]
)

array_propeties(a)


array = 
 [[11. 12. 13.]]
dimension =  2
shape =  (1, 3)
data type = float64
size =  3

array = 
 [[11. 12. 13.]]
dimension =  2
shape =  (1, 3)
data type = float32
size =  3

array = 
 [[11 12 13]]
dimension =  2
shape =  (1, 3)
data type = int64
size =  3

array = 
 [[11. 12. 13.]]
dimension =  2
shape =  (1, 3)
data type = float64
size =  3



In [40]:
a = np.array([
    [21],
    [22],
    [31],
    [0]
], dtype='float32')

array_propeties(a)

array = 
 [[21.]
 [22.]
 [31.]
 [ 0.]]
dimension =  2
shape =  (4, 1)
data type = float32
size =  4



In [41]:
## unsigned integer in 8 bits, uint8 datatype
# Min value is 0 and max value is 255 because 8 bit can only hold max 11111111 in 8 bit which is 255.


a = np.array([
    [21],
    [22],
    [31],
    [0]
], dtype='uint8')

array_propeties(a)

# int8 is a signed 8 bit
# min value is -128
# max is 127

array = 
 [[21]
 [22]
 [31]
 [ 0]]
dimension =  2
shape =  (4, 1)
data type = uint8
size =  4



In [47]:
## np.arange is similar to range()
import numpy as np

# seq_a = array of 1 to 10-1
seq_a = np.arange(1,10)
array_propeties(seq_a)

# like range(star,stop,step) np.arange(start,stop,step)
seq_a = np.arange(1,10,2)
array_propeties(seq_a)

array = 
 [1 2 3 4 5 6 7 8 9]
dimension =  1
shape =  (9,)
data type = int32
size =  9

array = 
 [1 3 5 7 9]
dimension =  1
shape =  (5,)
data type = int32
size =  5



In [52]:
a10 = np.arange(10)
print(a10)
for n in range(10):
    print(n,end=' | ')


for n in a10:
    print(n,end=' | ')

[0 1 2 3 4 5 6 7 8 9]
0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 

In [55]:
start =1 
stop = 10+1
step =2
ar10b = np.arange(start,stop,step)

# np array datatype can be changed
ar10b = np.uint8(ar10b)
array_propeties(ar10b)

# np.arrange() can be used to replace range()
for n in ar10b:
    print(n,end=' | ')

array = 
 [1 3 5 7 9]
dimension =  1
shape =  (5,)
data type = uint8
size =  5

1 | 3 | 5 | 7 | 9 | 

## Class Activity

create an array of integers [0,5,15,...,100]

In [56]:
a100 = np.arange(0,100+1,5)
array_propeties(a100)


array = 
 [  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]
dimension =  1
shape =  (21,)
data type = int32
size =  21



## np.linspace()

In [57]:
# create array of floating point value of a specific size

import numpy as np
seq_a2 = np.linspace(1,10,15)
array_propeties(seq_a2)

array = 
 [ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
dimension =  1
shape =  (15,)
data type = float64
size =  15



In [64]:
import numpy as np
start = 0
stop = 10
size = 10

seq_a2 = np.linspace(start,stop,size)
array_propeties(seq_a2)

# when we stop counting at 10 but the size is 10(which mean last index is 9),
# the value other than start and stop are added with some value 
# so the total will still be the value of stop(in this case 10)
# this is called an interpolation

start = 0
stop = 10
size = 11

# if size given is 11 then it is printed as how we normally count
# because the last index is 10 which fits value 0 to 10.
# so no interpolation happens here
seq_a2 = np.linspace(start,stop,size)
array_propeties(seq_a2)


## in summary depending on the start size and stop the value would look like this
# index-->value

# 0-->start
# 1-->1.x
# 2-->2.x
# .
# .
# stop-->stop

array = 
 [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
dimension =  1
shape =  (10,)
data type = float64
size =  10

array = 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
dimension =  1
shape =  (11,)
data type = float64
size =  11



In [68]:
# creating array of zeros

import numpy as np
rows=1
column = 10
arr0 = np.zeros((rows,column))
array_propeties(arr0)

# creating array of ones
import numpy as np
rows=1
column = 10
arr0 = np.zeros((rows,column))
array_propeties(arr0)


## their datatype are float64 by default, you can change them using dtype

rows=1
column = 10
arr0 = np.zeros((rows,column),dtype='int32')
array_propeties(arr0)

# creating array of ones
import numpy as np
rows=1
column = 10
arr0 = np.zeros((rows,column),dtype='uint8')
array_propeties(arr0)


array = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
dimension =  2
shape =  (1, 10)
data type = float64
size =  10

array = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
dimension =  2
shape =  (1, 10)
data type = float64
size =  10

array = 
 [[0 0 0 0 0 0 0 0 0 0]]
dimension =  2
shape =  (1, 10)
data type = int32
size =  10

array = 
 [[0 0 0 0 0 0 0 0 0 0]]
dimension =  2
shape =  (1, 10)
data type = uint8
size =  10



In [69]:
## creating multiple dimension np array

# 3d array of 4 by 5 by 3
zer_4_5_3 = np.zeros((4,5,3))

print(zer_4_5_3)
array_propeties(zer_4_5_3)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
array = 
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
dimension =  3
shape =  (4, 5, 3)
data type = float64
size =  60



In [70]:
# 4d array of 4 by 5 by 3 by 2
zer_4_5_3_2 = np.zeros((4,5,3,2))

print(zer_4_5_3_2)
array_propeties(zer_4_5_3_2)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]
array = 
 [[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

 

In [16]:
import numpy as np

a14 = np.arange(14+1)
# array_propeties(a14)
# reshape_a= a14.reshape((4,-1))
# array_propeties(reshape_a)


if  (a14.size % 4)==0:
    reshape_a = a14.reshape((4,-1))
    print(reshape_a.shape)
else:
    eshape_a = a14.reshape((3,-1))
    print(reshape_a.shape)


(3, 5)


## 2d array


In [5]:
## resize
import numpy as np
a1 = np.arange(1,17)
a2=np.resize(a1,(4,4))
array_propeties(a2)

array = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
dimension =  2
shape =  (4, 4)
data type = int32
size =  16



In [21]:
print(a2)
# get all elements in row 2
print(f"Elements in row 2 : {a2[1,:]}")
## the , after 1 in a2[1,:] means only, meaning we only print elemenets in 1st row(the second row) from all columns


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Elements in row 2 : [5 6 7 8]


In [23]:
# alternative get elents in row 2, this only work on 1d array
print("Elements in row 2",a2[1])

Elements in row 2 [5 6 7 8]


In [24]:
# get all value in column 2 or dimension 2
print(f"Elements in col 2 = ", a2[:,1])

Elements in col 2 =  [ 2  6 10 14]


## 3d array


In [25]:
import numpy as np
a3 = np.arange(1,9).reshape((2,2,2))
array_propeties(a3)

array = 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimension =  3
shape =  (2, 2, 2)
data type = int32
size =  8



In [27]:
## accessing 3d array elements
print(a3[0,1,1])
#
print(a3[0,1,:]) # : means all, in this case it means print all values in 


4
[3 4]


## Changing Array Element


In [28]:
import numpy as np

a3x3 = np.arange(1,10).reshape((3,-1))

print(a3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
# print value 6
print(a3x3[1,2])

6


In [35]:
# change value 8 to 18
a3x3=np.array([[1,2,3],
 [4, 5, 6],
 [7, 8, 9]])
print(a3x3)
print(a3x3[2,1])

a3x3[2,1] = 18

print(a3x3)
print(a3x3[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
[[ 1  2  3]
 [ 4  5  6]
 [ 7 18  9]]
18


In [36]:
import numpy as np
a1 = np.arange(9)
array_propeties(a1)

print("Third elements: ",a1[2])

a1[2]= a1[2] ** 2

print('Third element squared: ', a1[2])

array = 
 [0 1 2 3 4 5 6 7 8]
dimension =  1
shape =  (9,)
data type = int32
size =  9

Third elements:  2
Third element squared:  4


In [37]:
# 3^2 = 9
3**2

9

## Class activity

1. create an array of shape(2,5) and another array b of shape (3,5).
2. create another array c = a
3. change array c row 2 array to sum of array a row2 and b row2.

In [44]:
a = np.arange(1,11).reshape((2,5))
array_propeties(a)

b = np.arange(1,15+1).reshape((3,5))
array_propeties(b)

c = np.copy(a)
array_propeties(c)

c[1,:] = a[1,:]+b[1,:]
print(c)

array = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dimension =  2
shape =  (2, 5)
data type = int32
size =  10

array = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
dimension =  2
shape =  (3, 5)
data type = int32
size =  15

array = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dimension =  2
shape =  (2, 5)
data type = int32
size =  10

[[ 1  2  3  4  5]
 [12 14 16 18 20]]


## ADVANCED NUMPY INDEXING AND OPERATIONS


## Array slicing

In [45]:
import numpy as np
# create random array with value from 0 to 1000 with shape 5 3
a5x3 = np.random.randint(0,1000,(5,3))

array_propeties(a5x3)

array = 
 [[789 378 531]
 [100 905 702]
 [572 344 814]
 [469 142 514]
 [441 935 295]]
dimension =  2
shape =  (5, 3)
data type = int32
size =  15



In [46]:
# print 142 from array a5x3
print(a5x3[3,1])

142


In [47]:
# Change 2D ARRAY TO 1D ARRAY
# change a5x3 to 1d

##using flatten
a53 = a5x3.flatten()
print(a53)
array_propeties(a53)

[789 378 531 100 905 702 572 344 814 469 142 514 441 935 295]
array = 
 [789 378 531 100 905 702 572 344 814 469 142 514 441 935 295]
dimension =  1
shape =  (15,)
data type = int32
size =  15



In [49]:
# 2d to n1d uasing reshape

a15x_= a5x3.reshape((15,-1))
array_propeties(a15x_)

a15x_= a5x3.reshape((1,15))
array_propeties(a15x_)

array = 
 [[789]
 [378]
 [531]
 [100]
 [905]
 [702]
 [572]
 [344]
 [814]
 [469]
 [142]
 [514]
 [441]
 [935]
 [295]]
dimension =  2
shape =  (15, 1)
data type = int32
size =  15

array = 
 [[789 378 531 100 905 702 572 344 814 469 142 514 441 935 295]]
dimension =  2
shape =  (1, 15)
data type = int32
size =  15



In [ ]:
# 2d arrray to 1 d using ravel
# different between flatten and ravel
# flatten make a copy of array and odify, 
# while ravel is a view of the original array, so changes make in ravel changes the otriginal array too.
a53b = a5x3.ravel()
array_propeties(a53b)

## class acivity

1. create an array of shape (5,5,3) of datatype float32
2. create an array of c, of 1dimension from array a

In [55]:
a = np.arange(75,dtype='float32').reshape(5,5,3)
# array_propeties(a)

a1d = a.flatten()
array_propeties(a1d)

array = 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74.]
dimension =  1
shape =  (75,)
data type = float32
size =  75



In [61]:
import numpy as np

a5 = np.arange(1,(5+1),dtype=np.float32)
print(a5)

#this one wont work
# a5x5x3 = a5.reshape((5,5,3))

#this will only return none
# a5x5x3 = a5.resize((5,5,3))
# print(a5x5x3)

#This will work, it will repeat the values to fill value to fit the new array size
a5x5x3 = np.resize(a5,(5,5,3))
print(a5x5x3)


[1. 2. 3. 4. 5.]
[[[1. 2. 3.]
  [4. 5. 1.]
  [2. 3. 4.]
  [5. 1. 2.]
  [3. 4. 5.]]

 [[1. 2. 3.]
  [4. 5. 1.]
  [2. 3. 4.]
  [5. 1. 2.]
  [3. 4. 5.]]

 [[1. 2. 3.]
  [4. 5. 1.]
  [2. 3. 4.]
  [5. 1. 2.]
  [3. 4. 5.]]

 [[1. 2. 3.]
  [4. 5. 1.]
  [2. 3. 4.]
  [5. 1. 2.]
  [3. 4. 5.]]

 [[1. 2. 3.]
  [4. 5. 1.]
  [2. 3. 4.]
  [5. 1. 2.]
  [3. 4. 5.]]]


In [ ]:
import numpy as np

start = 1
stop = 3
a3 =  np.arange

In [70]:
## NEGATIVE INDEX
stop = 9
a1= np.arange(stop)

print("first element ",a1[0])
# print by index counted from last index
print("first element ",a1[-9])


## SLICING
print("even number", a1[0:stop:2])
# a1[start:end:step]
print("odd number", a1[1:stop:2])



first element  0
first element  0
even number [0 2 4 6 8]
odd number [1 3 5 7]


In [75]:
# You can use this to print 2 to 7 but its tedious

a1d = np.arange(10)
# get 2 t0 7
a2i = a1d[2]
a3i = a1d[3]
a4i = a1d[4]
a5i = a1d[5]
a6i = a1d[6]
a7i = a1d[7]

result = np.array([a2i,a3i,a4i,a5i,a6i,a7i])
print(result)


# instead use slicing
a2to7 = a1d[2:(7+1)]
array_propeties(a2to7)

[2 3 4 5 6 7]
array = 
 [2 3 4 5 6 7]
dimension =  1
shape =  (6,)
data type = int32
size =  6



In [76]:
import numpy as np


a2d = np.arange(10)
a2d = np.resize(a2d,(5,5))

array_propeties(a2d)


array = 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]]
dimension =  2
shape =  (5, 5)
data type = int32
size =  25



In [84]:
# what is the value of row 2
#[5,6,7,8,9]
print(a2d[1,:])# from  row 2, prit all value in it
# this is the best way to get values from ro2 2 to 4
print(a2d[1:4,:])
#or this, but this one only work on 1d
print(a2d[1:4])

[5 6 7 8 9]
[[5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


In [104]:
a2d = np.arange(1,26)
a2d = np.resize(a2d,(5,5))
print(a2d)

# # get [7 8 9]
# print(a2d[1,2:])

# # get [12,13,14]
# print(a2d[2,2:])

# # [17,18,19]
# print(a2d[3,2:])

# or get them all at once
# start end step
# 
print(a2d[1:4,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [105]:
# start:stop:step
# step 2 on rows and 3 of columns
result = a2d[::2,::3]
print(result)

[[ 1  4]
 [11 14]
 [21 24]]


In [108]:
bool_odd = np.array([False,True,False,True,False,True,False,True])

print(bool_odd.index())

SyntaxError: invalid syntax (Temp/ipykernel_4476/1909649448.py, line 3)

In [117]:
import numpy as np
a9 = np.arange(1,10)

In [123]:
i_even=np.array([1,3,5,7])
i_odd =np.array([0,2,4,6,8])


bool_odd = np.array([True,False,True,False,True,False,True,False,True])
bool_even = np.array([False,True,False,True,False,True,False,True,False])

print(a9[i_even])
print(a9[i_odd])
print(a9[bool_even])
print(a9[bool_odd])

[2 4 6 8]
[1 3 5 7 9]
[2 4 6 8]
[1 3 5 7 9]


## Class activity
1. Write the index for even number contain in the my_arr below
    28=[0,1],22=[0,5]
    50 =[1,0],92=[1,1],66 = [1,2],98 = [1,3],74 = [1,6]
    44=[2,0],60=[2,5],98[2,6]
    96=[3,0],38=[3,1]
    8=[4,3],66=[4,4],92=[4,5],62=[4,6]

2. write index of number divisible by 5.
75 = [0,0]
50 = [1,0]
85= [2,2],35 = [2,3],60 = [2,4]
55 =[3,2]

In [124]:
import numpy as np

my_arr = np.random.randint(1,100,(5,7))
array_propeties(my_arr)

array = 
 [[61  2 41  6 37 56 55]
 [47 22  4 47 98 94 86]
 [40 45  5 81 77 16 31]
 [18 33 17 57 15 27 17]
 [64 91 58 67 62  7 23]]
dimension =  2
shape =  (5, 7)
data type = int32
size =  35



In [132]:
# each value are remainder of og value divide by 5
ibooldiv5 = my_arr % 5

array_propeties(ibooldiv5)
# assign boolean value True if value is now 0, and False otherwise
ibooldiv5 = ibooldiv5 == 0
array_propeties(ibooldiv5)

array = 
 [[1 2 1 1 2 1 0]
 [2 2 4 2 3 4 1]
 [0 0 0 1 2 1 1]
 [3 3 2 2 0 2 2]
 [4 1 3 2 2 2 3]]
dimension =  2
shape =  (5, 7)
data type = int32
size =  35

array = 
 [[False False False False False False  True]
 [False False False False False False False]
 [ True  True  True False False False False]
 [False False False False  True False False]
 [False False False False False False False]]
dimension =  2
shape =  (5, 7)
data type = bool
size =  35



In [133]:
# use the new boolean array for indexing
result = my_arr[ibooldiv5]
print(result)

[55 40 45  5 15]
