## Linear Algebra

general form

$$
A.x=b
$$

$$


In [22]:
def array_propeties(a,str=""):
    print(str)
    print("array = \n", a)
    print("dimension = ", a.ndim)
    print("shape = ",a.shape)
    print("data type =",a.dtype)
    print("size = ", a.size)
    print()

# class activity

create an array of the system of equation above for A, and b

In [3]:
import numpy as np

A = np.array([[11,12,13,-14],
             [21,22,23,-24],
             [31,32,33,-34],
             [41,42,43,-44]])
b = np.array([[1],
             [2],
             [3],
             [4]])


array_propeties(A)


array_propeties(b)

# if we add extradimension on A 
A = np.array([[[11,12,13,-14],
             [21,22,23,-24],
             [31,32,33,-34],
             [41,42,43,-44]]])

array_propeties(A)

# NP.SQUEEZE reduce the extra dimension if possible
AA = np.squeeze(A)
array_propeties(AA)

array = 
 [[ 11  12  13 -14]
 [ 21  22  23 -24]
 [ 31  32  33 -34]
 [ 41  42  43 -44]]
dimension =  2
shape =  (4, 4)
data type = int32
size =  16

array = 
 [[1]
 [2]
 [3]
 [4]]
dimension =  2
shape =  (4, 1)
data type = int32
size =  4

array = 
 [[[ 11  12  13 -14]
  [ 21  22  23 -24]
  [ 31  32  33 -34]
  [ 41  42  43 -44]]]
dimension =  3
shape =  (1, 4, 4)
data type = int32
size =  16

array = 
 [[ 11  12  13 -14]
 [ 21  22  23 -24]
 [ 31  32  33 -34]
 [ 41  42  43 -44]]
dimension =  2
shape =  (4, 4)
data type = int32
size =  16



In [4]:
b = np.array([1,2,3,4])
array_propeties(b)

# Transpose on 1d doesnt change anything, if on other it will change col to row  and row to col
bT = np.transpose(b)
array_propeties(bT)


# reshape

bb = b.reshape((4,1))
array_propeties(bb)

array = 
 [1 2 3 4]
dimension =  1
shape =  (4,)
data type = int32
size =  4

array = 
 [1 2 3 4]
dimension =  1
shape =  (4,)
data type = int32
size =  4

array = 
 [[1]
 [2]
 [3]
 [4]]
dimension =  2
shape =  (4, 1)
data type = int32
size =  4



In [ ]:
#A.x -b
# x = b/A
# x = A^-1 .b

In [5]:
import numpy as np

A = np.array([[3,-3,-4],
             [1,-1,-1],
             [2,-1,4]
            ])


b = np.array([[1],
              [2],
              [3]
             ])

             

In [6]:
import numpy as np
x = np.linalg.solve(A, b)
array_propeties(x)

array = 
 [[-24.]
 [-31.]
 [  5.]]
dimension =  2
shape =  (3, 1)
data type = float64
size =  3



In [18]:
## Class Activity

# check if the solution above is correct, using the second equation of the system
# linear equation.

# round(3*x[0,0]-3*x[1,0]-4*x[2,0])== b[0]  

1*x[0,0]-1*x[1,0]-1*x[2,0] 

1.9999999999999982

In [26]:
# using incvers of A

from numpy import linalg

A = np.array([[3,-3,-4],
             [1,-1,-1],
             [2,-1,4]
            ])


b = np.array([[1],
              [2],
              [3]
             ])


inv_of_A = linalg.inv(A)
array_propeties(inv_of_A,'inv_of_A')

# A ^ -1 .b
x = inv_of_A @ b

# x = inv_of_A.dot(b)
array_propeties(x,"inv_of_A @ b")

# alternatively
x1 = inv_of_A.dot(b)
array_propeties(x1,"inv_of_A @ b")

#or
x2 = np.linalg.multi_dot([inv_of_A,b] )
array_propeties(x2,"inv_of_A @ b")


inv_of_A
array = 
 [[  5. -16.   1.]
 [  6. -20.   1.]
 [ -1.   3.   0.]]
dimension =  2
shape =  (3, 3)
data type = float64
size =  9

inv_of_A @ b
array = 
 [[-24.]
 [-31.]
 [  5.]]
dimension =  2
shape =  (3, 1)
data type = float64
size =  3

inv_of_A @ b
array = 
 [[-24.]
 [-31.]
 [  5.]]
dimension =  2
shape =  (3, 1)
data type = float64
size =  3

inv_of_A @ b
array = 
 [[-24.]
 [-31.]
 [  5.]]
dimension =  2
shape =  (3, 1)
data type = float64
size =  3



In [56]:
# crammer's rule or determinant method
from numpy.linalg import det

A = np.array([[3,-3,-4],
             [1,-1,-1],
             [2,-1,4]
            ])
# array_propeties(A)

b = np.array([[1],
              [2],
              [3]
             ])
# array_propeties(b)

D =det(A)
array_propeties(D)

(m,n) = A.shape
x = np.empty([3,1])
A_list = []
Di_list = []

for i in range(n):
    # get Ai
    # copy original array
    Ai = A.copy()
    # replace colun i in the new array with b
    Ai[:,i] = b[:,0]
    # store new array Ai in a list
    A_list.insert(i,Ai)
    # find determinants of Ai
    Di = det(Ai)
    # store Di in a list
    Di_list.insert(i,Di)
    # compute xi
    x[i] = Di/D

array_propeties(x,"x")

print("A_list ", A_list)
print("Di_list ", Di_list)








array = 
 -0.9999999999999998
dimension =  0
shape =  ()
data type = float64
size =  1

x
array = 
 [[-24.]
 [-31.]
 [  5.]]
dimension =  2
shape =  (3, 1)
data type = float64
size =  3

A_list  [array([[ 1, -3, -4],
       [ 2, -1, -1],
       [ 3, -1,  4]]), array([[ 3,  1, -4],
       [ 1,  2, -1],
       [ 2,  3,  4]]), array([[ 3, -3,  1],
       [ 1, -1,  2],
       [ 2, -1,  3]])]
Di_list  [24.000000000000014, 31.0, -5.000000000000001]


In [ ]:

A1 = np.copy(A)
A1[:,0] = b.squeeze()
D1 = det(A1)
print(D1)

array_propeties(A1,'A1')


A2 = np.copy(A)
A2[:,1] = b.squeeze()
array_propeties(A2,'A2')
D2 = det(A2)
print(D2)
print("")


A3 = np.copy(A)
A3[:,2] = b.squeeze()
array_propeties(A3,'A3')
D3 = det(A3)
print(D3)


In [69]:
import numpy as np
A = np.random.randint(0,256,(4,4))
print(A)

B = np.random.randint(0,256,(4,4))

print("\nA+B == B+A")
print(A+B == B+A)

print("\nA-B == -(B-A)")
print(A-B == -(B-A))

C = A * B

print("\n C = A * B\n",C)

[[162 191 177   7]
 [178 190  90 158]
 [125 136 249  23]
 [ 54  84  34 117]]

A+B == B+A
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

A-B == -(B-A)
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

 C = A * B
 [[  324  7449 29913   182]
 [40762 16340 18090 21804]
 [ 2750  4896 17181  4439]
 [ 5130 17640  7344 15912]]


In [70]:
##Transpose

# change row values to columns and vise versa

import numpy as np

A = np.arange(1,10).reshape(3,3)

transpose_A = np.transpose(A)
array_propeties(A,"Array A")
array_propeties(transpose_A,"transpose of array A")

Array A
array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9

transpose of array A
array = 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9



In [77]:
b = np.arange(1,4).reshape(1,3)
array_propeties(b)
transpose_b = np.transpose(b)
array_propeties(transpose_b)


array = 
 [[1 2 3]]
dimension =  2
shape =  (1, 3)
data type = int32
size =  3


array = 
 [[1]
 [2]
 [3]]
dimension =  2
shape =  (3, 1)
data type = int32
size =  3



In [79]:
A = np.arange(1,10).reshape(3,3)
array_propeties(A,"A")
B = np.transpose(A)
array_propeties(B,"B")




A
array = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9

B
array = 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9



In [83]:
p1 = A + B 
array_propeties(p1,"A + B == B + A")
A + B  == B + A
array_propeties(A + B  == B + A)

A + B == B + A
array = 
 [[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9


array = 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
dimension =  2
shape =  (3, 3)
data type = bool
size =  9



In [86]:

array_propeties(p2,"A-B == -(B-A)")

array_propeties(A-B  == -(B-A))

A-B == -(B-A)
array = 
 [[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9


array = 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
dimension =  2
shape =  (3, 3)
data type = bool
size =  9



In [87]:
p3 = A * B 
array_propeties(p3,"A * B == B + A")
p3 == B + A
array_propeties(A * B == B + A)

A * B == B + A
array = 
 [[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9


array = 
 [[False False False]
 [False False False]
 [False False False]]
dimension =  2
shape =  (3, 3)
data type = bool
size =  9



In [89]:
p4 = A @ B 
array_propeties(p4,"A @ B ")
p4 =  B @ A
array_propeties(p4,"B @ A ")
array_propeties(A @ B ==  B @ A)

A @ B 
array = 
 [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9

B @ A 
array = 
 [[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
dimension =  2
shape =  (3, 3)
data type = int32
size =  9


array = 
 [[False False False]
 [False False False]
 [False False False]]
dimension =  2
shape =  (3, 3)
data type = bool
size =  9



In [101]:
# iDENTITY MATRIX

import numpy as np
a = np.array([
    [1,0],
    [0,1]
])
array_propeties(a,"a")

a1 = np.array([
    [1,2],
    [3,4]
])
array_propeties(a1,"a1")

a
array = 
 [[1 0]
 [0 1]]
dimension =  2
shape =  (2, 2)
data type = int32
size =  4

a1
array = 
 [[1 2]
 [3 4]]
dimension =  2
shape =  (2, 2)
data type = int32
size =  4



In [102]:
a * a1

array([[1, 0],
       [0, 4]])

In [103]:
a @ a1

array([[1, 2],
       [3, 4]])

In [104]:
A = np.arange(1,10).reshape(3,3)

B = np.transpose(A.copy())

print("A\n",A)
print("B\n",B)

A
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [105]:
m, n = A.shape

I = np.eye(n)
array_propeties(I,"I")

I
array = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dimension =  2
shape =  (3, 3)
data type = float64
size =  9



In [106]:
A @ I

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
I @ A

In [107]:
A @ I ==  I @ A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])